name: Weather Data Download

on:
  schedule:
    # Run every day at 18:12 UTC
    - cron: '12 18 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  run-weather-download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Set your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install project dependencies

      - name: Run Weather Data Download script
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            COPERNICUS_KEY: ${{ secrets.COPERNICUS_KEY }}
            ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
        run: |
          python Weather Data Download.py  # Execute your script
